### ISSUE TITLE
hope to see the code released

### ISSUE THREAD

**Issue by bsaint** [wzzheng/GenAD#1]
Greetings!
I thank you very much for your excellent work. It gives me a lot of inspiration. I can't wait to see the code released, it will help to have a clear picture of all the details. Will the code be released soon?

**Comment by wzzheng** [comment]
Thanks for your interest! We plan to release the code in one or two weeks. Stay tuned!

**Comment by noticeable** [comment]
one month later~!

**Comment by wzzheng** [comment]
We have released the code. Thanks for your patience!
