### ISSUE TITLE
unable to visualize the results using the tools/analysis_tools/visualization.py

### ISSUE THREAD

**Issue by basaanitha2naveenkumar** [wzzheng/GenAD#10]
tried visualization script after evaluation throws dimension mismatch  error

**Comment by zihan912** [comment]
I have met the same problem, have you solved that?

**Comment by YangS03** [comment]
Adding `fut_coord = fut_coord.squeeze(0)` before 
https://github.com/wzzheng/GenAD/blob/4000d2cd1aa595301be35e31a8d3755614d63785/projects/mmdet3d_plugin/core/bbox/structures/nuscenes_box.py#L268 could potentially solve the problem

**Comment by songruiqi** [comment]
The code has been updated. Please use the latest visualization code.

**Comment by HengLoveYi** [comment]
> Adding `fut_coord = fut_coord.squeeze(0)` before
> 
> https://github.com/wzzheng/GenAD/blob/4000d2cd1aa595301be35e31a8d3755614d63785/projects/mmdet3d_plugin/core/bbox/structures/nuscenes_box.py#L268
> 
> could potentially solve the problem

Hello sir,
   May I ask how you get the argument file of "--result-path"  for visualization.py to run it?  Thanks very much!
