### ISSUE TITLE
ERROR while evaling：expected 4-dimensional weight, but got 6-dimensional input of size instead

### ISSUE THREAD

**Issue by zihan912** [wzzheng/GenAD#12]
I have pretraiend the model for 60epochs, and want to use test.py to test and eval. However I got this error, could anyone help me solve this problem? 
![微信图片_20240625163548](https://github.com/wzzheng/GenAD/assets/140795886/fbc1ed52-fedc-4d75-a34e-34fb006a2b0c)

**Comment by songruiqi** [comment]
We have resubmitted an early version of the code, and the latest code is currently being organized.

**Comment by xuanyuxin** [comment]
I am still facing this problem. Does anyone know how to solve it? Thanks!
