### ISSUE TITLE
Results in VAD vs. GenAD

### ISSUE THREAD

**Issue by kemaloksuz** [wzzheng/GenAD#20]
Hello, thanks for the great work. 

I have a question regarding the performance of VAD in your paper vs VAD paper. 

VAD-Base performance in Table 1 of https://arxiv.org/pdf/2303.12077 is 0.72 for Average L2 and 0.22 for Average Collision Rate. However, they are 1.22 and 0.53 in Table 1 of your paper. There are similar gaps for VAD-Tiny as well.

I am probably missing something, but couldn't find out the reason. Could you please clarify this please?

Thanks

**Comment by songruiqi** [comment]
The issue lies in the way the evaluation metric is calculated. We are using the L2 calculation method consistent with ST-P3, while the alternative method only calculates the L2 value at a specific future moment rather than accumulating the value over time.

**Comment by songruiqi** [comment]
The issue lies in the way the evaluation metric is calculated. We are using the L2 calculation method consistent with ST-P3, while the alternative method only calculates the L2 value at a specific future moment rather than accumulating the value over time.

**Comment by songruiqi** [comment]
> Hello, thanks for the great work.
> 
> I have a question regarding the performance of VAD in your paper vs VAD paper.
> 
> VAD-Base performance in Table 1 of https://arxiv.org/pdf/2303.12077 is 0.72 for Average L2 and 0.22 for Average Collision Rate. However, they are 1.22 and 0.53 in Table 1 of your paper. There are similar gaps for VAD-Tiny as well.
> 
> I am probably missing something, but couldn't find out the reason. Could you please clarify this please?
> 
> Thanks

The issue lies in the way the evaluation metric is calculated. We are using the L2 calculation method consistent with ST-P3, while the alternative method only calculates the L2 value at a specific future moment rather than accumulating the value over time.

**Comment by kemaloksuz** [comment]
Thanks for the reply. I appreciate you answer.

Below is what I understood. Could you please confirm?

**ST-P3 or your way of calculation:** At time step t, you make predictions for the next 4 time intervals (got this number from ST-P3). Let's say t+1 to t+4. And you sum the L2 error of these 4 predictions. Finally, you average these sums over planning scenarios.

**VAD style evaluation:** At time step t, they also make multiple predictions similar to GenAD. Differently in evaluation, they only consider the L2 error of a single step (instead of you are summing) and average over them for the final metric. In this case, which prediction do they consider? Is this simply the L2 error of t+1?

I also looked into ST-P3 but couldn't find a precise definition of the measure. That is why, I requested the details. Feel free to point me to a code or a paper if it will be easier for you.

**Comment by songruiqi** [comment]
> Thanks for the reply. I appreciate you answer.
> 
> Below is what I understood. Could you please confirm?
> 
> **ST-P3 or your way of calculation:** At time step t, you make predictions for the next 4 time intervals (got this number from ST-P3). Let's say t+1 to t+4. And you sum the L2 error of these 4 predictions. Finally, you average these sums over planning scenarios.
> 
> **VAD style evaluation:** At time step t, they also make multiple predictions similar to GenAD. Differently in evaluation, they only consider the L2 error of a single step (instead of you are summing) and average over them for the final metric. In this case, which prediction do they consider? Is this simply the L2 error of t+1?
> 
> I also looked into ST-P3 but couldn't find a precise definition of the measure. That is why, I requested the details. Feel free to point me to a code or a paper if it will be easier for you.

**Comment by songruiqi** [comment]
That's right, you can refer to the evaluation code of UniAD. our evaluation will be consistent with UniAD.

**Comment by songruiqi** [comment]
> Thanks for the reply. I appreciate you answer.
> 
> Below is what I understood. Could you please confirm?
> 
> **ST-P3 or your way of calculation:** At time step t, you make predictions for the next 4 time intervals (got this number from ST-P3). Let's say t+1 to t+4. And you sum the L2 error of these 4 predictions. Finally, you average these sums over planning scenarios.
> 
> **VAD style evaluation:** At time step t, they also make multiple predictions similar to GenAD. Differently in evaluation, they only consider the L2 error of a single step (instead of you are summing) and average over them for the final metric. In this case, which prediction do they consider? Is this simply the L2 error of t+1?
> 
> I also looked into ST-P3 but couldn't find a precise definition of the measure. That is why, I requested the details. Feel free to point me to a code or a paper if it will be easier for you.

That's right, you can refer to the evaluation code of UniAD. our evaluation will be consistent with UniAD.
