### ISSUE TITLE
Pre-trained Check Point

### ISSUE THREAD

**Issue by sunstarchan** [wzzheng/GenAD#3]
Great work. Glad to see your sharing of training and evaluation code release. 

I went through the source code and I didn't find any checkpoint you trained for quick evaluation. 

BTW, I noticed that in the config file of GenAD, genad_nuscenes_train.pkl, GenAD_nuscenes_val.pkl and nuscenes_map_anns_val.json were used. So I would like to know how to generate them.

**Comment by songruiqi** [comment]
The pkl file has already been updated in the readme.
