### ISSUE TITLE
ModuleNotFoundError: No module named 'projects.mmdet3d_plugin.VAD'

### ISSUE THREAD

**Issue by yksu** [wzzheng/GenAD#4]
After I prepare the datasets, when I run the evaluation.
There is the following ERROR

ModuleNotFoundError: No module named 'projects.mmdet3d_plugin.VAD'

CUDA_VISIBLE_DEVICES=0 python tools/test.py projects/configs/GenAD/GenAD_config.py ./ckpts/resnet50-19c8e357.pth --launcher none --eval bbox --tmpdir ./outputs
Traceback (most recent call last):
  File "tools/test.py", line 24, in <module>
    from projects.mmdet3d_plugin.VAD.apis.test import custom_multi_gpu_test
ModuleNotFoundError: No module named 'projects.mmdet3d_plugin.VAD'

Do someone know what happen here?
Thanks!

**Comment by wang-jh18-SVM** [comment]
I change it to "projects.mmdet3d_plugin.GenAD.apis.test" and it works.
