### ISSUE TITLE
Can you provide the checkpoints

### ISSUE THREAD

**Issue by sskmx** [wzzheng/GenAD#6]
Great work! I would like to know if you will provide the checkpoints.

**Comment by yangxue-1** [comment]
wget https://download.pytorch.org/models/resnet50-19c8e357.pth

> Great work! I would like to know if you will provide the checkpoints.

**Comment by sskmx** [comment]
> wget https://download.pytorch.org/models/resnet50-19c8e357.pth
> 
> > Great work! I would like to know if you will provide the checkpoints.
Thank you. What I meant was whether you can provide the weights for genAD.

**Comment by sskmx** [comment]
> wget https://download.pytorch.org/models/resnet50-19c8e357.pth
> 
> > Great work! I would like to know if you will provide the checkpoints.

Thank you. What I meant was whether you can provide the weights for genAD.

**Comment by songruiqi** [comment]
The early version of the checkpoint has been added. Please check the readme.
