### ISSUE TITLE
GenAD training on OpenDV-2K dataset

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [wzzheng/GenAD#8]
Thanks for your great work ! 
And I want to ask if you have a plan to release another version of GenAD model and training code on OpenDV-2K dataset ?

**Comment by songruiqi** [comment]
Currently, there is no such plan.

**Comment by ringo-misu** [comment]
hi @Oh-Cest-la-vie 

is it possible that you should refer to the other [GenAD](https://github.com/OpenDriveLab/driveAGI?tab=readme-ov-file#genad-opendv-dataset-) instead? It seems that there are two `GenAD` works at the moment.

**Comment by Oh-Cest-la-vie** [comment]
@ringo-misu Yes, you are right. But I think that repo only have the code of process the datasets.
